## Project
name: tasty_bytes
version: "1.0"
config-version: 2
profile: tasty_bytes
flags:
  enable_iceberg_materializations: True


## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  tasty_bytes:
    staging:
      +database: DBT_DB
      +schema: DEMO_DEV
      +materialized: view
    marts:
      +database: DBT_DB
      +schema: DEMO_DEV
      +materialized: table
