tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: 'RF_BENCHMARK_TESTEUR'
      database: 'DBT_DB'
      schema: 'DEMO_DEV'
      warehouse: 'DEFAULT_WH'
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: 'RF_BENCHMARK_TESTEUR'
      database: 'DBT_DB'
      schema: 'DEMO_PROD'
      warehouse: 'DEFAULT_WH'